[package]
name = "catpic"
version = "0.0.1"
edition = "2021"
authors = ["Sergey <sergey+github@optimaltec.com>"]

[dependencies]
async-std = ">=1.12.0"
image = ">=0.25.0"
image_hasher = ">=2.0.0"
memmap2 = ">=0.9.4"
