[package]
name = "catpic"
version = "0.0.1"
edition = "2021"
authors = ["Sergey <sergey+github@optimaltec.com>"]

[dependencies]
async-std = "1.12.0"
image = "0.24.7"
image_hasher = "1.2.0"
memmap2 = "*"
